package validation

const (
	RuleRequired  = "required"
	RuleMinLength = "minlen="
	RuleMaxLength = "maxlen="
)

const (
	ErrorMessageRequired            = "%s is required"
	ErrorMessageInvalidEmail        = "%s is not a valid email address"
	ErrorMessageInvalidPhone        = "%s is not a valid phone number"
	ErrorMessageInvalidPassword     = "%s must contain at least 8 characters including uppercase, lowercase, number, and special character"
	ErrorMessageInvalidUsername     = "%s must be 3-16 characters and can only contain letters, numbers, and underscores"
	ErrorMessageInvalidURL          = "%s is not a valid URL"
	ErrorMessageInvalidIPv4         = "%s is not a valid IPv4 address"
	ErrorMessageInvalidDate         = "%s is not a valid date format (YYYY-MM-DD)"
	ErrorMessageInvalidAlphaNumeric = "%s must contain only letters and numbers"
	ErrorMessageInvalidUUID         = "%s is not a valid UUID"
	ErrorMessageInvalidJSON         = "%s is not a valid JSON"
	ErrorMessageInvalidHexColor     = "%s is not a valid hex color code"
	ErrorMessageInvalidCreditCard   = "%s is not a valid credit card number"
	ErrorMessageInvalidPostalCode   = "%s is not a valid postal code"
	ErrorMessageInvalidBase64       = "%s is not a valid base64 string"
	ErrorMessageOneOf               = "%s must be one of %s"
	ErrorMessageLowercase           = "%s must be lowercase"
	ErrorMessageUppercase           = "%s must be uppercase"
	ErrorMessageNumber              = "%s must be a number"
	ErrorMessageFloat               = "%s must be a float"
	ErrorMessageInt                 = "%s must be an integer"
	ErrorMessageMin                 = "%s must be greater than or equal to %d"
	ErrorMessageMax                 = "%s must be less than or equal to %d"
	ErrorMessageMinLength           = "%s must be at least %d characters long"
	ErrorMessageMaxLength           = "%s must be at most %d characters long"
	ErrorMessageGreaterThan         = "%s must be greater than %d"
	ErrorMessageLessThan            = "%s must be less than %d"
	ErrorMessageGreaterThanEqual    = "%s must be greater than or equal to %d"
	ErrorMessageLessThanEqual       = "%s must be less than or equal to %d"
	ErrorMessageGreaterThanEqualStr = "%s must be greater than or equal to %s"
	ErrorMessageLessThanEqualStr    = "%s must be less than or equal to %s"
	ErrorMessageNotEqual            = "%s must not be equal to %s"
	ErrorMessageNotEqualStr         = "%s must not be equal to %s"
	ErrorMessageNotIn               = "%s must not be in %s"
)
